title: My WildCat Studios Portfolio description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: ""
url: "https://Chrysanthemums-Stars.github.io"
theme: jekyll-theme-architect
